# -*- coding: utf-8 -*-
"""A transaction class to send and receive money and test it.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oi9EPFi-USTd9ouuVPoqBwCmM-Hk6cQO
"""

!pip install pycryptodome

import Crypto
import binascii
import datetime
import collections
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA

class Client:
    def __init__(self):
        random = Crypto.Random.new().read
        self._private_key = RSA.generate(1024, random)
        self._public_key = self._private_key.publickey()
        self._signer = PKCS1_v1_5.new(self._private_key)

    @property
    def identity(self):
        return binascii.hexlify(self._public_key.exportKey(format='DER')).decode('ascii')

class Transaction:
    def __init__(self, sender, receiver, value):
        self.sender = sender
        self.receiver = receiver
        self.value = value
        self.time = datetime.datetime.now()

    def to_dict(self):
        if self.sender == "Genesis":
            identity = "Genesis"
        else:
            identity = self.sender.identity
        return collections.OrderedDict({
            'sender': identity,
            'receiver': self.receiver,
            'value': self.value,
            'time': self.time
        })

    def sign_transaction(self):
        private_key = self.sender._private_key
        signer = PKCS1_v1_5.new(private_key)
        h = SHA.new(str(self.to_dict()).encode('utf8'))
        return binascii.hexlify(signer.sign(h)).decode('ascii')

# Create instances of clients
Shivam = Client()
Rahul = Client()

# Print client identities (public keys)
print("-" * 50)
print("Shivam Key")
print(Shivam.identity)

print("-" * 50)
print("Rahul Key")
print(Rahul.identity)

# Create a transaction
t = Transaction(Rahul, Shivam.identity, 10.0)

print("-" * 50)
print("Transaction Sign")
signature = t.sign_transaction()
print(signature)
print("-" * 50)