# -*- coding: utf-8 -*-
"""Create a mining function and test it.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oi9EPFi-USTd9ouuVPoqBwCmM-Hk6cQO
"""

!pip install pycryptodome

import hashlib

def sha256(message):
    return hashlib.sha256(message.encode("ascii")).hexdigest()

def mine(message, difficulty=1):
    prefix = "1" * difficulty
    for i in range(1000):
        digest = hashlib.sha256(f"{message}{i}".encode()).hexdigest()
        if digest.startswith(prefix):
            print(f"After {str(i)} iterations, found nonce: {digest}")
            break

# Example usage
mine("test message", 2)